# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Welcome to the 15th IEEE Pacific Visualization Symposium
email: "pvis2022oc at vislab cs tsukuba ac jp"
description: >- # this means to ignore newlines until "baseurl:"
  PacificVis 2022 will be held in the spring of 2022 at Tsukuba, Japan.
author: publicity
baseurl: "/pvis2022" # the subpath of your site, e.g. /blog
url: "https://pvis2022.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PacificVis
facebook_username: PacificVis
github_username:  jekyll

# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic"

plugins:
  - jekyll-feed
# - jekyll-include-cache

collections_dir: _collections

collections:
  cfp:
    output: true
    permalink: /:collection/:path/
  program:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image:
        #path: 'assets/images/tsukuba_center_wide.jpg'
        path: 'assets/images/intro-image/intro-night.jpg'
  - scope:
      path: "_collections/_cfp"
    values:
      collection: cfp
      layout: page
      image:
        #path: 'assets/images/tsukuba_center_wide.jpg'
        path: 'assets/images/intro-image/intro-morning.jpg'
  - scope:
      path: "_collections/_program"
    values:
      collection: program
      layout: page
      image:
        #path: 'assets/images/tsukuba_center_wide.jpg'
        path: 'assets/images/intro-image/intro-morning.jpg'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - bin/
  - etc/
  - pvis2022
  - Readme.md
  - theme/
  - work/
